# Generated by Django 5.1.2 on 2024-11-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(default='linux', max_length=50)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('file', models.FileField(upload_to='files/AppFile/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
